### ISSUE TITLE
Exporting types

### ISSUE THREAD

**Issue by Artrix9095** [MattPlays/AniAPI.js#4]
So Im trying to use this SDK in typescript... and i find it very difficult to make this library cooperate with type checking because I don't have the actual types for most of the api responses... 
example: 
![image](https://user-images.githubusercontent.com/39530102/156087871-c3c3cc3c-0923-4b13-80e5-511d05993b00.png)
there's no real convenient way to check if I got an anime or not, or to at least make it type safe. if you were to export the types (such as the interface `Anime` in this scenario), doing something like
```ts
import { Anime } from '@mattplays/aniapi'

const res = await API.Anime.Random(10);

const data = res.data as Anime
```
Doing this could go a long way in making production level projects easier.  Thanks!

**Comment by MattPlays** [comment]
@Artrix9095 In a fix Im about to release for this, hopefully you can do
```typescript
import { API, Anime } from '@mattplays/aniapi'

const res = await API.Anime.Random(10);

const data = res.data as Anime
```
